<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="keywords" content="">
<meta name="description" content="">
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
<link rel="icon" href="/assets/images/favicon.ico" type="image/x-icon" />
<link rel="shortcut icon" href="/assets/images/favicon.ico" type="image/x-icon" />